@AbapCatalog.sqlViewName: 'ZI_PRT_MASTER'
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'CDS View for Production Resource Master Data'
define view entity ZI_PRT_MASTERDATA as select from crfh {
  key objty as ObjectType,
  key objid as ObjectId,
  key zaehl as Counter,
  fhmar as MaterialNumber,
  objty_v as ObjectTypeVariant,
  objid_v as ObjectIdVariant,
  loekz as DeletionIndicator,
  datuv as ValidFromDate,
  datub as ValidToDate,
  aennr as ChangeNumber,
  annam as ChangedByUser,
  andat as ChangedOnDate,
  aenam as ChangedByUserName,
  aedat as ChangedOn,
  brgru as PlantGroup,
  status as Status,
  kzkbl as IndicatorKzkbl,
  stowk as StorageLocation,
  stort as StorageType,
  baseh as BaseUnit,
  steuf as SpecialStockIndicator,
  steuf_ref as SpecialStockReference,
  fgru1 as ObjectClass1,
  fgru2 as ObjectClass2,
  planv as PlanningType,
  ktsch as CalendarType,
  ktsch_ref as CalendarReference,
  bzoffb as QuantityOffset1,
  bzoffb_ref as QuantityOffsetReference1,
  offstb as OffsetQuantity1,
  ehoffb as OffsetUnit1,
  offstb_ref as OffsetUnitReference1,
  bzoffe as QuantityOffset2,
  bzoffe_ref as QuantityOffsetReference2,
  offste as OffsetQuantity2,
  ehoffe as OffsetUnit2,
  offste_ref as OffsetUnitReference2,
  mgform as MeasuringPoint,
  mgform_ref as MeasuringPointReference,
  ewform as MaintenanceForm,
  ewform_ref as MaintenanceFormReference,
  par01 as Parameter01,
  par02 as Parameter02,
  par03 as Parameter03,
  par04 as Parameter04,
  par05 as Parameter05,
  par06 as Parameter06,
  paru1 as ParameterUnit01,
  paru2 as ParameterUnit02,
  paru3 as ParameterUnit03,
  paru4 as ParameterUnit04,
  paru5 as ParameterUnit05,
  paru6 as ParameterUnit06,
  parv1 as ParameterValue01,
  parv2 as ParameterValue02,
  parv3 as ParameterValue03,
  parv4 as ParameterValue04,
  parv5 as ParameterValue05,
  parv6 as ParameterValue06,
  registrable as Registrable
}